name: thunder_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/AbdAlftahSalem/Build-API-Collection.git

environment:
  sdk: ">=3.6.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  args: ^2.2.2
  dio: ^5.3.2

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0

executables:
  thunder_api: thunder_api