name: thunder_api
description: "A Dart package to build API collections directly from code with detailed annotations."
version: 1.0.1
repository: https://github.com/AbdAlftahSalem/Build-API-Collection.git

environment:
  sdk: ^3.2.0-134.0.dev

# Add regular dependencies here.
dependencies:
  args: ^2.2.2
  dio: ^5.3.2

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0

executables:
  thunder_api: thunder_api
